let shopItemData = [
  {
    id: "a",
    name: "T-Shirt",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/T-Shirt.jpg",
  },
  {
    id: "b",
    name: "Tie",
    price: 15,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/Tie.jpg",
  },
  {
    id: "c",
    name: "Jeans",
    price: 60,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/Jeans.jpg",
  },
  {
    id: "d",
    name: "Cap",
    price: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/Cap.png",
  },
  {
    id: "e",
    name: "Socks",
    price: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/Socks.jpg",
  },
  {
    id: "f",
    name: "Jacket",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/Jacket.jpg",
  },
  {
    id: "g",
    name: "Coat",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/Coat.jpg",
  },
];
